### ISSUE TITLE
Sphinx 1.0.8 leads to an error

### ISSUE THREAD

**Issue by pabo3000** [sdouche/collective.recipe.sphinxbuilder#1]
If you use c.r.s in version 0.7.1, your buildout pulls Sphinx 1.0.8. When you run bin/sphinxbuilder (make html or make latex or ...) there is an error:

...
File "/home/pab/.buildout/eggs/Sphinx-1.0.8-py2.7.egg/sphinx/roles.py", line 129, in **call**
    set_role_source_info(inliner, lineno, refnode)
  File "/home/pab/.buildout/eggs/Sphinx-1.0.8-py2.7.egg/sphinx/util/nodes.py", line 114, in set_role_source_info
    inliner.reporter.locator(lineno)
AttributeError: Reporter instance has no attribute 'locator'

But if you pin Sphinx >= 1.1, no error will appear. 

This could be done by requirements of collective.recipe.sphinxbuilder.

**Comment by sdouche** [comment]
Thanks for submitting this bug. I was able to reproduce this on my machine (only with Sphinx 1.0.8, no problem with 1.0.7 or 1.1.x). Acting on your suggestion, I will update the dependency.
