### ISSUE TITLE
Python 3 update needed: will PR be accepted?

### ISSUE THREAD

**Issue by reinout** [sdouche/collective.recipe.sphinxbuilder#26]
This recipe is failing with a pretty standard setup.py-reads-the-readme unicode error:

```
  File "/tmp/easy_install-9hksyjve/collective.recipe.sphinxbuilder-0.8.2/setup.py", line 9, in read
    ])
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 180: ordinal not in range(128)
An error occurred when trying to install collective.recipe.sphinxbuilder 0.8.2. Look above this message     for any errors that were output by easy_install.
```

I can probably fix that quite soon, but.... is this project still alive? Will there be a new release if needed?

**Comment by sdouche** [comment]
Hi @reinout 
No time anymore for this project but I will happy to give you full access to PyPI. Do you want to be the new maintainer?

**Comment by reinout** [comment]
That's OK. 

My pypi account name is "reinout".

**Comment by reinout** [comment]
I assume keeping it here in your repo is handiest, right?

**Comment by sdouche** [comment]
@reinout Done, you're the new maintainer on PyPI.

**Comment by reinout** [comment]
Thanks! Can you give me edit rights here in this repo? (Assuming I shouldn't use my fork?)

**Comment by sdouche** [comment]
Why don't use your own fork? This repo is already a fork :). Change the doc to point out to the new repo and that's all.

**Comment by reinout** [comment]
Ah, ok :-)
